## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
auth:
  existingSecret: "database"
  ## @param auth.secretKeys.adminPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ## @param auth.secretKeys.userPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ## @param auth.secretKeys.replicationPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ##
  secretKeys:
    adminPasswordKey: postgres-password

primary:
  initdb:
    scriptsConfigMap: "postgres-init"
  persistence:
    existingClaim: "postgresql-pvc"

architecture: replication
readReplicas:
  replicaCount: 2
  persistence:
    existingClaim: "postgresql-pvc"
volumePermissions:
  enabled: true

