## @section Global parameters
## Please, note that this will override the parameters, including dependencies, configured to use the global value
auth:
  existingSecret: "database"
  ## @param auth.secretKeys.adminPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ## @param auth.secretKeys.userPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ## @param auth.secretKeys.replicationPasswordKey Name of key in existing secret to use for PostgreSQL credentials. Only used when `auth.existingSecret` is set.
  ##
  secretKeys:
    adminPasswordKey: postgres-password

primary:
  podAntiAffinityPreset: hard
  initdb:
    scriptsConfigMap: "postgres-init"
  persistence:
    storageClass: local-storage
architecture: replication
readReplicas:
  podAntiAffinityPreset: hard
  replicaCount: 3
  persistence:
    storageClass: local-storage
volumePermissions:
  enabled: true

