apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS product (
      product_id INT NOT NULL,
      name varchar(250) NOT NULL,
      PRIMARY KEY (product_id)
    );
